# -*- coding: utf-8 -*-
"""EnergyConsumptionPredictionModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qczI5xqFIk_ExCf5nyRm2HuZFIYiFH2Z
"""



"""Energy Consumption Prediction Model
Energy Consumption & SEC Prediction (Prophet)




"""

# Energy Consumption & SEC Prediction (Prophet)

!pip install prophet

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from prophet import Prophet

# UPLOAD DATASET (AUTOMATION ENTRY POINT)

uploaded = files.upload()
file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)
print("Dataset uploaded:", file_name)

df.head()

# BASIC DATA CLEANING (REQUIRED)


# Remove duplicates
df.drop_duplicates(inplace=True)

# Handle date column safely
if "date" in df.columns:
    df["date"] = pd.to_datetime(df["date"])
elif "ds" in df.columns:
    df["ds"] = pd.to_datetime(df["ds"])

# Handle missing values
df.fillna(df.median(numeric_only=True), inplace=True)

# Clean only if raw refinery data
required_cols = ["electricity_kwh", "steam_usage", "fuel_usage", "production_tons"]
if all(col in df.columns for col in required_cols):
    df = df[
        (df["electricity_kwh"] > 0) &
        (df["steam_usage"] > 0) &
        (df["fuel_usage"] > 0) &
        (df["production_tons"] > 0)
    ]

print("Cleaning completed")

df.info()

# FEATURE ENGINEERING (VERY IMPORTANT)



# Total energy
df["total_energy"] = (
    df["electricity_kwh"] +
    df["steam_usage"] +
    df["fuel_usage"]
)

# SEC
df["SEC"] = df["total_energy"] / df["production_tons"]

df.head()

# AGGREGATE DATA (TIME-SERIES FORMAT)
# Daily aggregation (best for refinery planning)


daily_df = df.groupby("date").agg({
    "total_energy": "sum",
    "SEC": "mean"
}).reset_index()

daily_df.head()

# PREPARE DATA FOR PROPHET (FORMAT RULE)
# Prophet requires:
# ds → date
# y → value to predict
# 🔹 ENERGY FORECAST DATASET

# TRAIN ENERGY CONSUMPTION MODEL


energy_ts = daily_df.rename(columns={
    "date": "ds",
    "total_energy": "y"
})

energy_model = Prophet(
    yearly_seasonality=True,
    weekly_seasonality=True,
    changepoint_prior_scale=0.1
)

energy_model.fit(energy_ts)

# FORECAST FUTURE ENERGY (NEXT 30 DAYS)


future_energy = energy_model.make_future_dataframe(periods=30)
energy_forecast = energy_model.predict(future_energy)


energy_forecast.head()

# VISUALIZE ENERGY FORECAST 📊


energy_model.plot(energy_forecast)
plt.title("Refinery Energy Consumption Forecast")
plt.xlabel("Date")
plt.ylabel("Total Energy")
plt.show()

# PREPARE SEC FORECAST DATASET

# SEC FORECAST MODEL (AUTO)


sec_ts = daily_df.rename(columns={
    "date": "ds",
    "SEC": "y"
})

sec_model = Prophet(
    yearly_seasonality=True,
    changepoint_prior_scale=0.1
)

sec_model.fit(sec_ts)

# FORECAST FUTURE SEC


# SEC FORECAST + VISUAL


future_sec = sec_model.make_future_dataframe(periods=30)
sec_forecast = sec_model.predict(future_sec)

sec_model.plot(sec_forecast)
plt.title("Automated SEC Forecast")
plt.show()

sec_forecast.head()

# VISUALIZE SEC FORECAST


sec_model.plot(sec_forecast)
plt.title("Refinery SEC Forecast")
plt.xlabel("Date")
plt.ylabel("SEC")
plt.show()

#AUTO SAVE OUTPUT FILES


energy_forecast[["ds", "yhat", "yhat_lower", "yhat_upper"]].to_csv(
    "energy_forecast.csv", index=False
)

sec_forecast[["ds", "yhat", "yhat_lower", "yhat_upper"]].to_csv(
    "sec_forecast.csv", index=False
)

print("Forecast files saved automatically")

# DOWNLOAD RESULTS
# files.download("energy_forecast.csv")
# files.download("sec_forecast.csv")